apiVersion: v1
data:
  cosign.key: LS0tLS1CRUdJTiBFTkNSWVBURUQgU0lHU1RPUkUgUFJJVkFURSBLRVktLS0tLQpleUpyWkdZaU9uc2libUZ0WlNJNkluTmpjbmx3ZENJc0luQmhjbUZ0Y3lJNmV5Sk9Jam8yTlRVek5pd2ljaUk2Ck9Dd2ljQ0k2TVgwc0luTmhiSFFpT2lKdkwyeE9UUzh5TTBadmFYZFBMMlI1Tm1oWmEzUTVabXBKVHpkSmVHZHoKWVV0VGJ6RTFRVzlzZVRKSlBTSjlMQ0pqYVhCb1pYSWlPbnNpYm1GdFpTSTZJbTVoWTJ3dmMyVmpjbVYwWW05NApJaXdpYm05dVkyVWlPaUp5U1c1T1RXUlpka05QZVVGbk5FOU5MMWxJY1hkMGIyTnROVGRqY21JdlF5SjlMQ0pqCmFYQm9aWEowWlhoMElqb2liME5oTkZGdWJuQlJVbmwyZVhJNU9VRkZPVVI0Y21kR1VXOTBWbWc0TlhKbk0yaE0KVlZWVGRrZGxibmhFYlROWk5YRk1RblJ5ZUhKRVVuUXJNVTFaWldWR2QzaGtNakFyYURKVk5EbGhZMjVhVGs1UgpXblpOWkZrMldYVXhTR2RLVURKYWVFVnBkRVUxUkRaM1IxWkVUMU5hVDBOUVRERkxVMUF6ZUhsTWJFY3dNbTV6CmFIUmhWRFZyV0VaWGVHWlFLMDVGYjB0Rk9EQTJLMlZNWlZOQ2EzbGhVbFZRU3pscVNYUnJiMUF3WkRRd1QzUjYKVTBVMWJtVnlTSFZwVTJKNloxWmtNMnBSTm5STFQyRmhWMmM5UFNKOQotLS0tLUVORCBFTkNSWVBURUQgU0lHU1RPUkUgUFJJVkFURSBLRVktLS0tLQo=
  cosign.password: eHh4
  cosign.pub: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFYWFsNEtCL2xlMUQvQUxTMFJUZGJTbS9IdFJJeQpVZW9sUno3U1g0cDZuY2M2Nmg4RG9CbGdCZ3QzOGYyZ3lDWDl2elZuWUhKWm5ETENldHgxRnM0TmdRPT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: signing-secrets
  namespace: openshift-pipelines
type: Opaque
